name: Build (Windows / macOS / Linux)

on:
  workflow_call:
    inputs:
      project_dir:
        required: false
        type: string
        default: "."
    secrets:
      checkout_ssh_key:
        required: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-15-intel]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.checkout_ssh_key }}
      
      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python requirements
        working-directory: ${{ inputs.project_dir }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/go/requirements.txt

      - name: Build project
        working-directory: ${{ inputs.project_dir }}
        run: python scripts/go/main.py -y

      - name: Package build
        working-directory: ${{ inputs.project_dir }}
        run: python scripts/project_packager.py package

      # NOTE: we no longer use zip files because github will zip the artifacts for us automatically
      - name: Find packaged build directory
        id: build_dir
        shell: bash
        working-directory: ${{ inputs.project_dir }}
        run: |
          python scripts/project_packager.py name >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_dir.outputs.build_dir }}
          path: ${{ inputs.project_dir }}/${{ steps.build_dir.outputs.build_dir }}

